<?php

namespace app\widgets\rate;
use yii\base\Widget;

class Rate extends Widget
{
    public function run()
    {
        return  'salom';
//        parent::run(); // TODO: Change the autogenerated stub
    }
}